const { modelNames } = require("mongoose")
x = module.exports;

x.descript= [
    'acrobatic',
    'adventurous',
    'brave',
    'bright',
    'brilliant',
    'concrete',
    'conventional',
    'delirious',
    'foolhardy',
    'gregarious',
    'grim',
    'handsome',
    'handy',
    'intelligent',    
    'intrepid',
    'joyful',
    'jubilant',
    'keen',
    'kooky',
    'lanky',
    'lazy',
    'limp',
    'luxurious',
    'mediocre',
    'mellow',
    'miserable',
    'nocturnal',
    'organic',
    'ordinary',
    'powerless',
    'practical',
    'precious',
    'quirky',
    'radiant',
    'rustic',
    'sly',
    'sophisticated',
    'stunning',
    'tattered',
    'thorny',
    'verdant'
]

x.places = [
    "Above Rocks",
    "Albert Town",
    "Alexandria",	
    "Alligator Pond",	
    "Anchovy",
    "Annotto Bay",	
    "Balaclava",
    "Bamboo",
    "Bath",
    "Bethel Town",	
    "Black River",
    "Bluefields",		
    "Bog Walk",	
    "Brompton",	
    "Brown's Town",	
    "Buff Bay",	
    "Bull Savanna",		
    "Cambridge",	
    "Cascade",
    "Cave Valley",
    "Chapelton",
    "Christiana",	
    "Claremont",
    "Clark's Town",	
    "Coleyville",
    "Constant Spring",	
    "Croft's Hill",	
    "Darliston",	
    "Discovery Bay",	
    "Duncans",
    "Easington",	
    "Ewarton",
    "Falmouth",	
    "Frankfield",	
    "Frome",	
    "Gayle",	
    "Golden Grove",	
    "Gordon Town",		
    "Grange Hill",
    "Green Island",	
    "Guy's Hill",	
    "Highgate",	
    "Hope Bay",	
    "Hopewell",	
    "Islington",	
    "Kellits",	
    "Lacovia",	
    "Lionel Town",	
    "Little London",	
    "Lluidas Vale",	
    "Lucea",	
    "Lucky Hill",	
    "Maggotty",	
    "Malvern",	
    "Manchionea",	
    "Maroon Town",	
    "Mavis Bank",	
    "Moneague",	
    "Moore Town",	
    "Morant Bay",		
    "Nain",	
    "Negril",	
    "Ocho Rios",	
    "Old Harbour Bay",	
    "Oracabessa",	
    "Osbourne Store",
    "Petersfield",
    "Point Hill",	
    "Port Maria",	
    "Port Royal",	
    "Porus",
    "Race Course",
    "Richmond",
    "Rio Bueno",
    "Riversdale",
    "Rocky Point",	
    "Runaway Bay",	
    "Sandy Bay",	
    "Sanguinetti",	
    "Santa Cruz",	
    "Seaford Town",	
    "Seaforth",
    "Siloah",	
    "Southfield",	
    "Spalding",	
    "Stony Hill",	
    "Trinity Ville",		
    "Ulster Spring",
    "Wakefield",
    "White House",
    "Williamsfield",
    "Yallahs",
    "Villages"
]

x.types = [
    "feild",  
    "forests", 
    "woodland", 
    "grassland", 
    "mountain", 
    "beach", 
    "swamp", 
    "cave", 
    "pond", 
    "cliff", 
    "river",
    "lake",
    "geyser"
]
